# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-07 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='qualification',
        ),
    ]
